### ISSUE TITLE
Annotation

### ISSUE THREAD

**Issue by HITxyer** [Maclory/Deep-Iterative-Collaboration#11]
Hi,thank you very much for your sharing the code, I have some confusion about how the .pkl in the annotation file is generated Looking forward to your reply.

**Comment by Steve-Tod** [comment]
Hi, thanks for your interest. 

We use OpenFace to generate 68 landmarks for CelebA faces, and use the official 5-landmark annotation to check the result(We only use 68-landmark annotations whose errors are smaller than a threshold). Based on the landmarks, we calculate the bounding boxes that can properly cover the face. Finally we put the bounding boxes and 68 landmarks in the pkl file.
