### ISSUE TITLE
The processing of image in HG model

### ISSUE THREAD

**Issue by LiangbinXie** [Maclory/Deep-Iterative-Collaboration#15]
Hi, when you train the HG model, what's the image processing? In my view, I think dividing 255 is necessaray, but do you substract the mean of images afterwards? If so, the mean of images is the same?

**Comment by Steve-Tod** [comment]
Hi, thank your for your interest in our work. You can find the the image processing steps in [HRLandmarkDataset.py](https://github.com/Maclory/Deep-Iterative-Collaboration/blob/5d3c271740ca3b9278b7566ad8489aaa7d5afbc0/code/data/HRLandmarkDataset.py).
As for image normalization, you can find the mean [here](https://github.com/Maclory/Deep-Iterative-Collaboration/blob/5d3c271740ca3b9278b7566ad8489aaa7d5afbc0/code/data/HRLandmarkDataset.py#L22). We subtract the image with the mean RGB of whole CelebA dataset(0.509, 0.424, 0.378).

**Comment by LiangbinXie** [comment]
Thanks for your kind reply, I still have some puzzle. I think your need to train the HG model, and then you use this model to detect facial landmarks in DIC arch. During **the training of HG model**, does you use the same image normalization in [HRLandmarkDataset.py](https://github.com/Maclory/Deep-Iterative-Collaboration/blob/5d3c271740ca3b9278b7566ad8489aaa7d5afbc0/code/data/HRLandmarkDataset.py)？

**Comment by LiangbinXie** [comment]
Thanks for your kind reply, but I still have some puzzle. I think you need to train the HG model in the first step, then train the DIC arch in the second step. So in the first step**(just FeedbackHourGlass arch)**, you mentioned that you follow this git [repo,](https://github.com/raymon-tian/hourglass-facekeypoints-detection) but what I found there about image processing is just dividing 255, with no image normalization. So I want to ask again whether you subtract the image with the mean RGB during the training of FeedbackHourGlass arch.
Sorry to bother you again, thanks!

**Comment by Steve-Tod** [comment]
I follow the network structure of the [repo](https://github.com/raymon-tian/hourglass-facekeypoints-detection), but training setting is different, you can follow my own [repo](https://github.com/Steve-Tod/hourglass-face-landmark) for face alignment with HourGlass network. From [here](https://github.com/Steve-Tod/hourglass-face-landmark/blob/7ccb81fff756a3001e48c3c3498399808c662d03/data/dataset.py#L17) you can see that I do subtract the mean.

**Comment by LiangbinXie** [comment]
OK, I see. Thanks for your kind reply~
