### ISSUE TITLE
Questions about inference

### ISSUE THREAD

**Issue by kevinzezel** [Maclory/Deep-Iterative-Collaboration#19]
Hi,

First of all confratulations!!

I ran the test.py with the celeb database images that have the HR and LR images successfully. But I would like to know if it is possible to run any other image LR only with face landmarks.

Thank you for your help!
Kevin

**Comment by Maclory** [comment]
Hi, thank you for your interest in our work. 

I think I didn't really get your point. Actually we don't need landmarks as input for inference.
