### ISSUE TITLE
Can not reproduce the result using default option and model

### ISSUE THREAD

**Issue by Glorainow** [Maclory/Deep-Iterative-Collaboration#2]
I changed the pathes of model and images in the **test_DICGAN_Helen.json** and **test_DIC_Helen.json**, then ran test.py use these options as told in README. But the results are really terrrible. Did I miss something? The data used to test the program is Helen that downloaded as asked and preprocessed as said in https://github.com/Maclory/Deep-Iterative-Collaboration/issues/1. The models I used were DIC_Helen.pth and DICGAN_Helen.pth respectively.

**Comment by Maclory** [comment]
Hi, we have uploaded our testing sets of CelebA and Helen to [Google Drive](https://drive.google.com/open?id=1Q1T1smMDRMO1NcjkxbZvotOX93YIVp5e) and [Baidu Drive](https://pan.baidu.com/s/14zJ_lY8iFmk3csHYZmut7Q) (extraction code: 6qhx). We will also upload our code for data preprocessing soon.
