### ISSUE TITLE
How to training own custom dataset?

### ISSUE THREAD

**Issue by ss24cs** [Maclory/Deep-Iterative-Collaboration#21]
Hi, buddy, thank your wonderful demo. I want to train own images instead of  CelebA and Helen dataset. How to modify the cfg file? Could you tell me some suggest? Please.

**Comment by Steve-Tod** [comment]
Hi, to train on your own dataset, first, you need to use [OpenFace](https://github.com/TadasBaltrusaitis/OpenFace) to extract face landmarks.

**Comment by ss24cs** [comment]
> Hi, to train on your own dataset, first, you need to use [OpenFace](https://github.com/TadasBaltrusaitis/OpenFace) to extract face landmarks.

Ok, I will try it, thx.
