### ISSUE TITLE
The annotation Helen_test.pkl doesn't have keys of 'landmark' and 'bbox'.

### ISSUE THREAD

**Issue by hdjsjyl** [Maclory/Deep-Iterative-Collaboration#25]
Hi authors, thanks for your excellent work. I am a newer for face super-resolution. 
Now I am trying to train DIC model by using Helen dataset, but for the Helen_train.json, the 'info_path' in the 'Helen_train.json', if I set it as 'Helen_test.pkl' file, it shows an error 'IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices'. Any advice will be appreciated, thank you!

**Comment by Steve-Tod** [comment]
Hi, I'm not sure what's happening here, can you show me the full log? Like which line of code throw this error?

My current guess is that we didn't put landmark info for test images(landmark is not needed for the test, while needed for training), so you can't train on the test set.

**Comment by nanmehta** [comment]
hey is the issue resolved, me too getting the same problem

**Comment by wfxiaobo** [comment]
Hello  authors， I meet the same problem.

**Comment by Liu0329** [comment]
anyone can tell where to get the pkl file ?

**Comment by wfxiaobo** [comment]
The author gave the link









------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Liu0329"<notifications@github.com&gt;; 
发送时间: 2021年2月22日(星期一) 下午2:05
收件人: "Maclory/Deep-Iterative-Collaboration"<Deep-Iterative-Collaboration@noreply.github.com&gt;; 
抄送: "魏峰"<499638409@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [Maclory/Deep-Iterative-Collaboration] The annotation Helen_test.pkl doesn&#39;t have keys of &#39;landmark&#39; and &#39;bbox&#39;. (#25)





 
anyone can tell where to get the pkl file ?

**Comment by Liu0329** [comment]
@wfxiaobo Got it. But have you solved the issue ?

**Comment by wfxiaobo** [comment]
We generate Helen pkl by ourselves



发自我的iPhone


------------------ Original ------------------

**Comment by Onepengpeng** [comment]
> @wfxiaobo Got it. But have you solved the issue ?

Hi,I meet the same problem.Have you solved the issue ?

**Comment by Onepengpeng** [comment]
> We generate Helen pkl by ourselves 发自我的iPhone
> […](#)
> ------------------ Original ------------------ From: Liu0329 <notifications@github.com&gt; Date: Mon,Feb 22,2021 3:08 PM To: Maclory/Deep-Iterative-Collaboration <Deep-Iterative-Collaboration@noreply.github.com&gt; Cc: wfxiaobo <499638409@qq.com&gt;, Mention <mention@noreply.github.com&gt; Subject: Re: [Maclory/Deep-Iterative-Collaboration] The annotation Helen_test.pkl doesn't have keys of 'landmark' and 'bbox'. (#25) @wfxiaobo Got it. But have you solved the issue ? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

How to generate Helen pkl by myself?Thanks.

**Comment by suntianlei2019102967** [comment]
> > We generate Helen pkl by ourselves 发自我的iPhone
> > […](#)
> > ------------------ Original ------------------ From: Liu0329 <[notifications@github.com](mailto:notifications@github.com)> Date: Mon,Feb 22,2021 3:08 PM To: Maclory/Deep-Iterative-Collaboration <[Deep-Iterative-Collaboration@noreply.github.com](mailto:Deep-Iterative-Collaboration@noreply.github.com)> Cc: wfxiaobo <[499638409@qq.com](mailto:499638409@qq.com)>, Mention <[mention@noreply.github.com](mailto:mention@noreply.github.com)> Subject: Re: [Maclory/Deep-Iterative-Collaboration] The annotation Helen_test.pkl doesn't have keys of 'landmark' and 'bbox'. (#25) @wfxiaobo Got it. But have you solved the issue ? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> How to generate Helen pkl by myself?Thanks.



> > We generate Helen pkl by ourselves 发自我的iPhone
> > […](#)
> > ------------------ Original ------------------ From: Liu0329 <[notifications@github.com](mailto:notifications@github.com)> Date: Mon,Feb 22,2021 3:08 PM To: Maclory/Deep-Iterative-Collaboration <[Deep-Iterative-Collaboration@noreply.github.com](mailto:Deep-Iterative-Collaboration@noreply.github.com)> Cc: wfxiaobo <[499638409@qq.com](mailto:499638409@qq.com)>, Mention <[mention@noreply.github.com](mailto:mention@noreply.github.com)> Subject: Re: [Maclory/Deep-Iterative-Collaboration] The annotation Helen_test.pkl doesn't have keys of 'landmark' and 'bbox'. (#25) @wfxiaobo Got it. But have you solved the issue ? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.
> 
> How to generate Helen pkl by myself?Thanks.

I meet the same problem.Have you solved the issue?
