### ISSUE TITLE
question about evaluation and test?

### ISSUE THREAD

**Issue by yasuobinggan** [Maclory/Deep-Iterative-Collaboration#26]
Hi, During the test and train of Helen dataset, I find that the optimal model is chosen from the evaluation results, but I found that the evaluation and test used the same set of data, which made me a little confused. Is this reasonable?

**Comment by Steve-Tod** [comment]
Hi, it is a little tricky. Since the size of Helen dataset is too small, it's hard to train&eval on this set, so we just evaluate on the train set.

**Comment by yasuobinggan** [comment]
OK, thank you very much!
