### ISSUE TITLE
How to make Low Resolution image? 

### ISSUE THREAD

**Issue by choieq** [Maclory/Deep-Iterative-Collaboration#29]
Hi, Thank you for your research. 

**I wonder how LR image made it.**

When i reproduce your code, down-sample cv2.resize(img, cv2.INTERCUBIC).
Then, result is weird. 

Please, answer me. 
Thank you.

**Comment by Steve-Tod** [comment]
Hi, please use the following code:
```python
from PIL import Image

HR = Image.open(path/to/HR)
LR = HR.resize(lr_shape, resample=Image.BICUBIC)
```

**Comment by choieq** [comment]
thank you it works properly :)
