### ISSUE TITLE
Has anyone tested the effect on other datasets?

### ISSUE THREAD

**Issue by MARIOXIAN** [Maclory/Deep-Iterative-Collaboration#30]
I first sampled the LFW dataset, then used the pre-training model of the original author to perform super-resolution on the LFW dataset, and serious artifacts appeared in the face image. 

Has anyone tested the effect on other face data sets? Would you like to know what caused it? Thank you!
![0105_05_0](https://user-images.githubusercontent.com/41474708/99633523-0436a980-2a7a-11eb-85bd-a504773a07dc.jpg)
![0105_05_1](https://user-images.githubusercontent.com/41474708/99633533-0862c700-2a7a-11eb-8aaa-0b70b7467c2c.jpg)
![0112_03_0](https://user-images.githubusercontent.com/41474708/99633539-0b5db780-2a7a-11eb-8043-ad22fa8c32fb.jpg)

**Comment by MARIOXIAN** [comment]
Has anybody done any experiments on face recognition rates?

**Comment by kabutohui** [comment]
I got the same problem when I downsampled CelebA dataset to 16x16. That is weird. However, the authors created the LR by downsampling HR images just with bicubic degradation in their paper.

**Comment by MARIOXIAN** [comment]
> 当我将CelebA数据集下采样到16x16时，我遇到了同样的问题。真奇怪 但是，作者通过对HR图像进行降采样来创建LR，只是在论文中出现了三次三次降级。

**Comment by MARIOXIAN** [comment]
> 当我将CelebA数据集下采样到16x16时，我遇到了同样的问题。真奇怪 但是，作者通过对HR图像进行降采样来创建LR，只是在论文中出现了三次三次降级。

**Comment by MARIOXIAN** [comment]
> I got the same problem when I downsampled CelebA dataset to 16x16. That is weird. However, the authors created the LR by downsampling HR images just with bicubic degradation in their paper.

我看了您的资料介绍，我就说中文吧，英文不太好。我观察了作者给的测试集，是用的png格式的CelebA中的人脸图像来测试的，在png格式下，把图像下采样后，超分的测试结果是很不错的。所以我把LFW的数据也转成png格式的了，结果伪影减少了，各项指标也很不错，具体是什么原因还不知道，希望能帮到你。

**Comment by Steve-Tod** [comment]
Hi there, please use png images. We found jpg compression leads to information loss in low res images, where any bit of image is very important.

**Comment by kabutohui** [comment]
Thanks, @MARIOXIAN , @Steve-Tod . Here's another tips,  when you create LR png files from HR images, please use `Image` instead of `OpenCV`.
