### ISSUE TITLE
How to define the training/testing set

### ISSUE THREAD

**Issue by jingang2020** [Maclory/Deep-Iterative-Collaboration#34]
Thanks for your excellent work. If I want to train the model on Helen from scratch. Should I take all of the 5 parts from All images on Helen website as the training set? Or whether the testing set is selected from these images, so that this part needs to be excluded in advance? How can I get the list of training images.

**Comment by Steve-Tod** [comment]
Hi there, to compare with FSRNet, we adopt the same train/test split as them. The test list can be found here: https://github.com/tyshiwo/FSRNet/blob/master/data/fileList_helen_lr.txt
