### ISSUE TITLE
Can I run the test code with cpu?

### ISSUE THREAD

**Issue by Leo9113** [Maclory/Deep-Iterative-Collaboration#37]
Can I run the test code with cpu?

**Comment by Maclory** [comment]
Yes,  but the inference speed may be slow.

**Comment by suntianlei2019102967** [comment]
> Yes, but the inference speed may be slow.


Is it modified in the json file？

**Comment by Leo9113** [comment]
> Yes, but the inference speed may be slow.

How to modify it
