### ISSUE TITLE
更改scale的一些问题

### ISSUE THREAD

**Issue by JIANG3330** [Maclory/Deep-Iterative-Collaboration#38]
你好作者。我想尝试使用32*32的LR图片放大4x到SR图片的时候，我遇到问题了。我已经将Option/train.json的scale=8, lr_size=32,
在dic_arch.py里也添加了
```python
self.upscale_factor == 4:
    # with PixelShuffle at start, need to upscale 2x only
    stride = 2
    padding = 1
    kernel_size = 4
```
但是我尝试运行的时候, 发现attentive fusion块表示维度不对应，我在论文观察结构中知道Face Super-Resolution分支中，LR图片经过
Pixel Shuffle后相比于之前的16*16size，输入进当前分支的Conv 1*1的时候，因为image的size已经成了64*64的大小，他在输入
Attentive Fusion时候与featmap的32*32维度不匹配了，于是乎我定位到StackedHourGlass.py文件，尝试更改pre_conv_block块，
尝试让其生成一个64*64的feat map和feature；在尝试去掉MaxPool2D层，但是失败了，报错信息显示预加载的HG模型权重不匹配。
我要重新训练一个HG模型权重吗?? 但是预加载模型不影响Face Alignment分支的A1部分块(即在StackedHourGlass.py/self.pre_conv_block)吧?
请问一下作者，给我一些指导意见吗？ 感谢万分

**Comment by Maclory** [comment]
你好，我认为可以改SR分支也可以改alignment分支，相对来说改SR分支代码更容易但精度可能有影响，改alignment分支性能可能会更好，但是有可能需要重新训练HG模型的权重。
