### ISSUE TITLE
How to generate SR image with my own LR image

### ISSUE THREAD

**Issue by fyaft2012** [Maclory/Deep-Iterative-Collaboration#39]
Hi @Maclory and @Steve-Tod , thanks for your excellent work! I can successfully test the model using provided test datasets (CelebA|Helen).
However, I want to test my own LR image without anymore information (no according SR image or landmark annotation), how could I use your model to generate according SR image? Which file should I run or modify?
Thank you in advance!

**Comment by Steve-Tod** [comment]
Please follow the testing instructions [here](https://github.com/Maclory/Deep-Iterative-Collaboration#testing). Face landmarks are not needed.
