### ISSUE TITLE
作者您好，我在跑训练模型代码的时候，代码里info path 这个路径下的.pkl文件，我用的是您提供的，但是报了以下错误，请问这个文件需要自己去生成吗？希望您能解答，万分感谢。

### ISSUE THREAD

**Issue by Aichiniuroumian** [Maclory/Deep-Iterative-Collaboration#47]
===> Training Epoch: [1/8]...  Learning Rate: 0.000100
Traceback (most recent call last):
  File "train.py", line 196, in <module>
    main()
  File "train.py", line 98, in main
    for _, batch in enumerate(train_loader):
  File "/usr/local/anaconda3/envs/DIC/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/usr/local/anaconda3/envs/DIC/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/usr/local/anaconda3/envs/DIC/lib/python3.7/site-packages/torch/_utils.py", line 369, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/DIC/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/anaconda3/envs/DIC/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/anaconda3/envs/DIC/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/wang107552002794/Deep-Iterative-Collaboration/code/data/HRLandmarkDataset.py", line 45, in __getitem__
    hr, hr_path = self._load_file(idx) # Numpy float32, HWC, RGB, [0,255]
  File "/home/wang107552002794/Deep-Iterative-Collaboration/code/data/HRLandmarkDataset.py", line 85, in _load_file
    hr = util_dataset.read_img(hr_path, self.opt['data_type'])
  File "/home/wang107552002794/Deep-Iterative-Collaboration/code/data/util_dataset.py", line 18, in read_img
    img = cv2.imread(path)[:, :, ::-1]
TypeError: 'NoneType' object is not subscriptable

**Comment by Maclory** [comment]
你好，这种情况应该是路径不对造成的，可以检查一下数据集图片的路径是否正确

**Comment by Aichiniuroumian** [comment]
作者您好，非常感谢您能够在百忙中解答我的问题。目前这个问题已经解决。我还想向您请教另一个问题：我在训练Helen数据集的时候，发现在您提供的.pkl文件中，并没有Helen_val.pkl文件，所以请问训练Helen数据集的时候在train_DIC_Helen.json这个文件下，info_path的路径该填什么呢？我填您提供的Helen_test.pkl会报错这个错误， 'IndexError: only integers, slices (:), ellipsis (...), numpy.newaxis (None) and integer or boolean arrays are valid indices'. 希望您能解答，万分感谢~&nbsp; 祝您工作愉快！


------------------ 原始邮件 ------------------
发件人:                                                                                                                        "Maclory/Deep-Iterative-Collaboration"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年2月28日(星期一) 上午9:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Maclory/Deep-Iterative-Collaboration] 作者您好，我在跑训练模型代码的时候，代码里info path 这个路径下的.pkl文件，我用的是您提供的，但是报了以下错误，请问这个文件需要自己去生成吗？希望您能解答，万分感谢。 (Issue #47)





 
你好，这种情况应该是路径不对造成的，可以检查一下数据集图片的路径是否正确
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Leo9113** [comment]
> 作者您好，非常感谢您能够在百忙中解答我的问题。目前这个问题已经解决。我还想向您请教另一个问题：我在训练Helen数据集的时候，发现在您提供的.pkl文件中，并没有Helen_val.pkl文件，所以请问训练Helen数据集的时候在train_DIC_Helen.json这个文件下，info_path的路径该填什么呢？我填您提供的Helen_test.pkl会报错这个错误， 'IndexError: only integers, slices (:), ellipsis (...), numpy.newaxis (None) and integer or boolean arrays are valid indices'. 希望您能解答，万分感谢~&nbsp; 祝您工作愉快！
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Maclory/Deep-Iterative-Collaboration" ***@***.***&gt;; 发送时间:&nbsp;2022年2月28日(星期一) 上午9:39 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [Maclory/Deep-Iterative-Collaboration] 作者您好，我在跑训练模型代码的时候，代码里info path 这个路径下的.pkl文件，我用的是您提供的，但是报了以下错误，请问这个文件需要自己去生成吗？希望您能解答，万分感谢。 (Issue #47) 你好，这种情况应该是路径不对造成的，可以检查一下数据集图片的路径是否正确 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

请问您解决这个问题了吗，我也遇到了同样的问题

**Comment by Aichiniuroumian** [comment]
> > 作者您好，非常感谢您能够在百忙中解答我的问题。目前这个问题已经解决。我还想向您请教另一个问题：我在训练Helen数据集的时候，发现在您提供的.pkl文件中，并没有Helen_val.pkl文件，所以请问训练Helen数据集的时候在train_DIC_Helen.json这个文件下，info_path的路径该填什么呢？我填您提供的Helen_test.pkl会报错这个错误， 'IndexError: only integers, slices (:), ellipsis (...), numpy.newaxis (None) and integer or boolean arrays are valid indices'. 希望您能解答，万分感谢~  祝您工作愉快！
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: "Maclory/Deep-Iterative-Collaboration" _**@**_._**>; 发送时间: 2022年2月28日(星期一) 上午9:39 _**@**_.**_>; _**@**_._**_**@**_.**_>; 主题: Re: [Maclory/Deep-Iterative-Collaboration] 作者您好，我在跑训练模型代码的时候，代码里info path 这个路径下的.pkl文件，我用的是您提供的，但是报了以下错误，请问这个文件需要自己去生成吗？希望您能解答，万分感谢。 (Issue #47) 你好，这种情况应该是路径不对造成的，可以检查一下数据集图片的路径是否正确 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: _**@**_.***>
> 
> 请问您解决这个问题了吗，我也遇到了同样的问题

已经解决了，我的qq:1143298540 ，希望可能帮到你
