### ISSUE TITLE
关于数据集人脸关键点的问题

### ISSUE THREAD

**Issue by xxh96** [Maclory/Deep-Iterative-Collaboration#5]
您好作者，能分享下您的人脸关键点数据集制作代码吗？（pkl）
请问您选择的是哪种模型得到标准人脸关键点数据的？是模型中的HG吗？
如果使用预先设置好的数据集（lr+hr+人脸关键点）三种数据作为模型的输入，是否能加快训练呢？

**Comment by Steve-Tod** [comment]
我们用的[openface](https://github.com/TadasBaltrusaitis/OpenFace)来得到关键点数据的。
然后输入的话用的是hr+landmark，lr是在线降采样的，不过实际对速度影响不大，GPU 利用率很高。

**Comment by xxh96** [comment]
非常感谢您的回复
