### ISSUE TITLE
Upscaling Factor of 4

### ISSUE THREAD

**Issue by ZeeRizvee** [Maclory/Deep-Iterative-Collaboration#9]
Greetings.

This is an interesting work. Congratulations to the authors on achieving this. I have been able to test the algorithm for up scaling images 8 times. I was wondering, has the algorithm been trained for 4 times up scaling too? If so, can you provide the pre-trained weights for it?

Thank you.

**Comment by Maclory** [comment]
Hi, thank you for your interest in our work. We have not trained a model of 4x upscaling. However, I think it worth trying and it can be easily achieved by modifying the upsampling layer.
